@startuml

Rectangle  #GreenYellow{
archimate #Technology "Existing PostgreSQL \n     Database Setup" as no <<technology-node>>

archimate #white " Backup Data \n and Scheme " as R <<application-service>>

archimate #White " Latest Version \n   PostgreSQL \n    installation" as R1 <<application-service>>





archimate #white "StopServices \n   and Config \n  " as d1 <<application-component>>

archimate #White "Install Latest \n     Version \n Dependencies" as d2 <<application-component>>




archimate #WhiteSmoke "Restore Data \n   and Scheme " as db1 <<application-component>>

archimate #White "Initialized New \n Database Cluster" as db2 <<application-component>>

archimate #White "Configure New \n   PostgreSQL\n installation" as db3 <<application-component>>

archimate #White "  Test the New \n PostgreSQL \n Setup" as db4 <<application-component>>

archimate #White "Start Services with \n     New Config" as db5 <<application-component>>




R --> [d1]
R1 --> [d2]


d1 --> [db1]
d2 --> [db2]
db1 -->[db3]
db2 -->[db4]
db3 -->[db5]

}
no -->R
no -->R1

@enduml